end2end_eval:
  metrics:
    text_block:
      metric:
        - Edit_dist
        # - BLEU
        # - METEOR
      # group:
        # - text_language: text_en
          # text_background: white
        # - text_language: text_simplified_chinese
    display_formula:
      metric:
        - Edit_dist
        # - CDM
    table:
      metric:
        - TEDS
        - Edit_dist
      # group:
      #   - with_span: True
      #   - with_span: False
    reading_order:
      metric:
        - Edit_dist
  dataset:
    dataset_name: end2end_dataset
    ground_truth:
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/middle/docparse_1103_subset.json
      data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/middle/ocr-main-1113.json
    prediction:
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results_htmltable/GOT
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results_htmltable/gpt4o
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results_htmltable/internvl76b
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results_htmltable/marker
      data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results_htmltable/mathpix1108
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results_htmltable/nougat
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results_htmltable/mineru1111_docyolo
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results_htmltable/mineru1111_layoutlm
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results_htmltable/QwenVL_htmltable_full
    match_method: no_split
    # match_method: simple_match
    # filter: 
    #   language: english
