end2end_eval:
  metrics:
    text_block:
      metric:
        - Edit_dist
        # - BLEU
        # - METEOR
    display_formula:
      metric:
        - Edit_dist
        - CDM
    table:
      metric:
        - TEDS
        - Edit_dist
    reading_order:
      metric:
        - Edit_dist
  dataset:
    dataset_name: end2end_dataset
    ground_truth:
      data_path: ./tools/model_infer/OmniDocBench_dataset/OmniDocBench.json
    prediction:
      #change this to your GPT-corrected results folder
      data_path: ./demo_data/microsoft_ocr_results_gpt_processed/run_2025-07-30_10-43-01/corrected_gpt
    match_method: quick_match
    # filter: 
    #   language: english
