end2end_eval:
  metrics:
    text_block:
      metric:
        - Edit_dist
        # - BLEU
        # - METEOR
      # group:
        # - text_language: text_en
          # text_background: white
        # - text_language: text_simplified_chinese
    display_formula:
      metric:
        - Edit_dist
        # - CDM
    table:
      metric:
        - TEDS
        - Edit_dist
      # group:
      #   - with_span: True
      #   - with_span: False
    reading_order:
      metric:
        - Edit_dist
  dataset:
    dataset_name: end2end_dataset
    ground_truth:
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/middle/docparse_1103_subset.json
      data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/middle/docparse_1107.json
    prediction:
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results/mineru
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results/nougat
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results/internvl76b_htmltable
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results/qwen2vl_htmltable
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results/got
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results/marker
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results/mineru1108
      data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results/mathpix1108
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results/gpt4o
    # match_method: no_split
    # match_method: simple_match
    # filter: 
    #   language: english
