end2end_eval:
  metrics:
    text_block:
      - Edit_dist
      # - BLEU
    inline_formula:
      - Edit_dist
      # - CDM
    display_formula:
      - Edit_dist
      # - CDM
    table:
      - TEDS
    reading_order:
      - Edit_dist
      - Move_dist
  dataset:
    dataset_name: end2end_dataset
    ground_truth:
      data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/middle/docparse_1025_subset.json
    prediction:
      data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/results/mathpix_subset
    # match_method: simple_match
    match_method: quick_match
    # match_method: full_match