detection_eval:   # layout
  metrics:
    - COCODet
  dataset: 
    dataset_name: detection_dataset_simple_format
    ground_truth:
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/middle/ocr-main-1114.json
      data_path: /mnt/hwfile/opendatalab/zhaozhiyuan/OmniDocBench/docparse_1107.json
    prediction:
      data_path: /mnt/petrelfs/ouyanglinke/DocParseEval/det_test/predictions.json
    filter: 
      data_source: exam_paper
  categories:
    eval_cat:
      block_level:
        - isolate_formula    # Display formula (this is a layout display formula, lower priority than 14)
      span_level:
        - inline_formula     # inline formula
    gt_cat_mapping:    # 这个字段主要是用来统一不同的模型之间类别的conflict的
      equation_isolated: isolate_formula
      equation_inline: inline_formula
    pred_cat_mapping:
      interline_formula: isolate_formula
      inline_formula: inline_formula