detection_eval:
  metrics:
    - COCODet
  dataset: 
    dataset_name: detection_dataset_simple_format
    ground_truth:
      data_path: ../demo_data/omnidocbench_demo/OmniDocBench_demo.json
    prediction:
      data_path: ../demo_data/detection/prediction.json
    filter: 
      data_source: exam_paper
  categories:
    eval_cat:
      block_level:
        - isolate_formula    # Display formula (this is a layout display formula, lower priority than 14)
      span_level:
        - inline_formula     # inline formula
    gt_cat_mapping:    
      equation_isolated: isolate_formula
      equation_inline: inline_formula
    pred_cat_mapping:
      interline_formula: isolate_formula
      inline_formula: inline_formula