recogition_eval: # Text
  metrics:
    - Edit_dist
    - CDM
    # - BLEU
  dataset:
    dataset_name: omidocbench_single_module_dataset
    ground_truth:
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/Formula_result/docparse_1107_formula_pix2tex.json
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/Formula_result/docparse_1107_formula_GOT.json
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/Formula_result/docparse_1110_formula_mathpix.json
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/Formula_result/docparse_1107_formula_internvl.json
      data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/Formula_result/docparse1107_formula_qwenvl_checked.json
      data_key: latex
      category_filter: ['equation_isolated']
    prediction:
      # data_key: pix2tex_pred
      # data_key: got_pred
      data_key: pred
      # data_key: internvl_pred
    category_type: formula