detection_eval:   # layout
  metrics:
    - COCODet
  dataset: 
    dataset_name: detection_dataset_simple_format
    ground_truth:
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/middle/ocr-main-1114.json
      data_path: /mnt/hwfile/opendatalab/zhaozhiyuan/OmniDocBench/docparse_1107.json
    prediction:
      data_path: /mnt/petrelfs/ouyanglinke/DocParseEval/det_test/predictions.json
    filter: 
      data_source: exam_paper
  categories:
    gt_cat_mapping:    # 这个字段主要是用来统一不同的模型之间类别的conflict的
      figure_footnote: figure_footnote
      figure_caption: figure_caption 
      page_number: abandon 
      header: abandon 
      page_footnote: abandon
      table_footnote: table_footnote 
      code_txt: figure 
      equation_caption: formula_caption 
      equation_isolated: isolate_formula
      table: table 
      refernece: text 
      table_caption: table_caption 
      figure: figure 
      title: title 
      text_block: text 
      footer: abandon
    pred_cat_mapping:
      title : title
      plain text: text
      abandon: abandon
      figure: figure
      figure_caption: figure_caption
      table: table
      table_caption: table_caption
      table_footnote: table_footnote
      isolate_formula: isolate_formula
      formula_caption: formula_caption