end2end_eval:
  metrics:
    text_block:
      metric:
        - Edit_dist
        # - METEOR
        # - BLEU
    display_formula:
      metric:
        - Edit_dist
        - CDM
    table:
      metric:
        - TEDS
        - Edit_dist
    reading_order:
      metric:
        - Edit_dist
      # - Move_dist
  dataset:
    dataset_name: md2md_dataset
    ground_truth:
      data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/md1120
      page_info: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/middle/ocr-main-1114.json
      # data_path: /mnt/petrelfs/ouyanglinke/CDM_match/test_data/gt
    prediction:
      data_path: /mnt/petrelfs/ouyanglinke/CDM_match/benchmark/result1120/gpt4o_long_prompt
    match_method: simple_match
    # match_method: no_split
    # match_method: quick_match
    # match_method: full_match